### ISSUE TITLE
Replace FMOD with Wwise

### ISSUE THREAD

**Issue by PanosK92** [PanosK92/SpartanEngine#107]
Wwise seems to be free for any project with a production budget less than 250K: https://www.audiokinetic.com/en/pricing/

It's probably why other open-source engines use it.

Need to replace FMOD.

**Comment by nexovec** [comment]
Hey Panos, if you could elaborate on why that's a good idea and what's bad about FMOD, that would be cool.

**Comment by PanosK92** [comment]
I was mostly focused on the license, the costs of shipping with a certain audio library and so on.
After further research, both FMOD and Wwise are similar in terms of licensing and also nobody is shipping a game anytime soon.
Therefore I will close this issue, it's a decision for the far future.
