### ISSUE TITLE
Incorrect quaternion multipliciation?

### ISSUE THREAD

**Issue by haikarainen** [PanosK92/SpartanEngine#112]
Compare the two lines of code below. The first one is from `Transform::SetRotation`, and the second one is from `Transform::Rotate`.

The first one seem to work how I expect quaternion multiplication to work. I.e. inverse multiplication, or `childRotation * parentRotation` to have the parent rotation applied first. From what I can tell, the second one seems to flip this concept though, and applies the rotation delta before it applies the current rotation. Is this a bug or am I just a bit slow today?

https://github.com/PanosK92/SpartanEngine/blob/383e6da89b7a2a9fb7f9e88e6b5ac0e92484b289/runtime/World/Components/Transform.cpp#L153

```c++
        SetRotationLocal(!HasParent() ? rotation : rotation * GetParent()->GetRotation().Inverse());
```

https://github.com/PanosK92/SpartanEngine/blob/383e6da89b7a2a9fb7f9e88e6b5ac0e92484b289/runtime/World/Components/Transform.cpp#L208

```c++
            SetRotationLocal((m_rotation_local * delta).Normalized());
```

**Comment by PanosK92** [comment]
You are correct, thank you for taking the time to bring this to my attention 👍🏻 

This [commit](https://github.com/PanosK92/SpartanEngine/commit/ea489dddd27d64c4d85d83616866e029c5d4d5ed) fixes it
