### ISSUE TITLE
Subsurface Scattering

### ISSUE THREAD

**Issue by rikseth** [PanosK92/SpartanEngine#12]
There must be a support for subsurface scattering

**Comment by rikseth** [comment]
there must be CLOTH SIMULATION

**Comment by rikseth** [comment]
What about CLOTH SIMULATION

**Comment by rikseth** [comment]
Which kind of project did you used to make the game in visual studio
Windows Desktop wizard
or 
Windows Desktop Application
or
Windows Console application
?????

**Comment by PanosK92** [comment]
I'm might be able to squeeze it into v0.31 but I can't tell for sure right now. However, cloth simulation is part of the physics subsystem (Bullet) and is relatively to expose in the engine, so, it will happen sooner or later.

Regarding your question, the type of project is not that important, it's only a template.
Pick whatever feels best and tweak it when the time comes.

**Comment by rikseth** [comment]
Thanks........

**Comment by rikseth** [comment]
but did you used visual studio or qt ide

**Comment by PanosK92** [comment]
Just the Visual Studio IDE, for both the engine's runtime and the editor (ImGui).

If it's of any help, when I first started, I had a look at tutorials like this one:
http://www.rastertek.com/tutdx11.html 😉

**Comment by PanosK92** [comment]
No worries.
Global illumination is listed in the roadmap as well, everything will happen.

**Comment by rikseth** [comment]
Why did you choose ImGui over Qt?

**Comment by PanosK92** [comment]
Multiple reasons, ImGui is:

- MIT licensed, which one of the most permissive licenses.
- Fast to develop with, I can have a window with some stuff in it, in seconds, literally.
- Easy to maintain, as the logic code and design code are one and the same.
- Platform independence, it can be implemented to run anywhere, which means that after adding Vulkan support, it should be possible to get the engine to run on other platforms.
- Very small, only a few files, Qt is a few GBs and includes a lot of stuff I don't need but can't remove.

This is what comes to mind now 🤔

**Comment by OdysseyCreations** [comment]
How did you managed the inputs when you were in QT framework?

**Comment by OdysseyCreations** [comment]
In directinput we need HINSTANCE to initialize the device. Where did you get that from?

**Comment by PanosK92** [comment]
Hi OdysseyCreations,

This issue is titled "Subsurface Scattering" and also has a "rendering" label. 
Your question belongs to a different issue as it's related to Qt/Input.
However, since this question is Qt related, you should google it instead.
The one line code answer will come up as the first result.

Thanks

**Comment by OdysseyCreations** [comment]
Which rendering API does PS4 uses?
Unreal engine and UNITY supports the PS4. But which API did they use?
You work in Sony right> therefore you must know this better than anyone.
What does it uses -> Directx, opengl, or some other api??

**Comment by OdysseyCreations** [comment]
I googled it but found that it does not support DirectX, then what does it support?

**Comment by PanosK92** [comment]
Well well well, welcome back OdysseyCreations, or should I say rikseth? 😄 

I googled what you googled and [this](https://en.wikipedia.org/wiki/PlayStation_4_system_software) is the first result that comes up.

I understand you are quite young and while I am happy to asnwer your questions, the conversation has escaped the context of this repository and could also be replaced by google searches. As a final warning, I would advice you to read on how to open an issue by clicking [here](https://github.com/PanosK92/Directus3D/issues/15).
