### ISSUE TITLE
Vulkan_SwapChain Resize Window has a problem, is made fence wait timeout. so need reset m_sync_index = std::numeric_limits<uint32_t>::max();

### ISSUE THREAD

**Issue by DUAN-SEAN** [PanosK92/SpartanEngine#144]
// Only resize if needed
        if (!force)
        {
            if (m_width == width && m_height == height)
                return;
        }

        // Save new dimensions
        m_width  = width;
        m_height = height;

        // Reset image index
        m_image_index          = numeric_limits<uint32_t>::max();
    	m_sync_index = std::numeric_limits<uint32_t>::max();

        Destroy();
        Create();
        AcquireNextImage();

**Comment by PanosK92** [comment]
Fixed. Thanks!

**Comment by DUAN-SEAN** [comment]
You're welcome. Thanks for all the help your engine has provided me.
