### ISSUE TITLE
Bug: opening a world crashes the engine

### ISSUE THREAD

**Issue by TheIronLefty** [PanosK92/SpartanEngine#146]
### Bug Report

**Issue:**
Engine Crash after loading any world 

**Steps to Reproduce:**
1. Open any world on RX Vega card.

**Expected Outcome:**
Engine loads the scene normally.

**Actual Outcome:**
Engine Crashed after loading any world

**Environment:**
- Operating System: Windows 10 Pro x64 22H2
- GPU AMD RX Vega 56 / 24.3.1 Driver
- CPU AMD R5 5600X

**Log.txt (if it exists) or screenshots:**
Spartan::RHI_CommandList::Blit: Assertion failed: source_blit_size.x <= destination_blit_size.x && source_blit_size.y <= destination_blit_size.y && "The source texture dimension(s) are larger than the those of the destination texture"

[log.txt](https://github.com/PanosK92/SpartanEngine/files/15248279/log.txt)

**Callstack:**

**Comment by TheIronLefty** [comment]
[inis.zip](https://github.com/PanosK92/SpartanEngine/files/15248501/inis.zip)

**Comment by PanosK92** [comment]
https://github.com/PanosK92/SpartanEngine/commit/060cdbda13ce7afe0098962f560c9938dc7bf77c fixes the issue.

I would appreciate if you could verify that it doesn't crash anymore so that I can close the issue.
