### ISSUE TITLE
C# scripting 

### ISSUE THREAD

**Issue by OdysseyCreations** [PanosK92/SpartanEngine#16]
In the road-map you have told that you are going to implement the C# scripting language for programming, What are you plannings for that? I mean that what is the compiler or the technique you are going to use?

[As you have told I have opened a new issue]
[Yes, I am pretty young currently in Class 9 but I like game development and I am making my own game engine, I have been using Unity and Unreal engine since Class 3, now I want to use my own game engine for game development I have went through many articles but I really need help from a real example]

**Comment by PanosK92** [comment]
The most common way, and the way that engines like Unity do it, is via Mono. 
You can read more about it [here](https://www.mono-project.com/docs/advanced/embedding/scripting/).

There are of course other options like [.Net Core](https://en.wikipedia.org/wiki/.NET_Core) and [CS-Script](http://www.csscript.net/)

Much better, opening a new issue keeps things clean and also allows other people with the same questions to avoid opening more issues 😃 School is okay but if you want to become a true master OdysseyCreations, you have to learn how to search for knowledge (like google) and teach yourself 😉
