### ISSUE TITLE
I can't run the engine because of an error.

### ISSUE THREAD

**Issue by raythegreat123** [PanosK92/SpartanEngine#163]
### Bug Report

**Issue:**
When I try running the engine, it produces an error. I have attached the screenshot below

**Steps to Reproduce:**
1. Build the generated solution.
2. Run spartan_vulkan_debug.exe file

**Expected Outcome:**
The engine should just open

**Actual Outcome:**
It produced an error that is shown down below

**Environment:**
- Operating System: Windows
- GPU: Intel(R) HD Graphics 520
- CPU: Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz   2.40 GHz

**Error:**
![image](https://github.com/user-attachments/assets/176492b8-e584-422e-b9de-a55a0971704f)

**Comment by PanosK92** [comment]
Hey there,

Your GPU came out way back in 2015 and only supports up to Vulkan 1.0, while the engine needs Vulkan 1.3.

You’ll need a GPU upgrade to get it working.

Thanks for checking out the engine!

**Comment by raythegreat123** [comment]
Okay thank you for your help
