### ISSUE TITLE
Shadow Issue

### ISSUE THREAD

**Issue by OdysseyCreations** [PanosK92/SpartanEngine#17]
![Capture](https://user-images.githubusercontent.com/47780708/55285378-c074c500-53a8-11e9-8cca-f8f60ba69e4e.JPG)

[I think the picture speaks for itself]
This is the shadow problem I was speaking about
In case of cube it is ok but in case of sphere this is the problem

**Comment by PanosK92** [comment]
Hi OdysseyCreations,

Shadows are indeed glitchy, both in terms of self-shadowing and when it comes to cascade blending.

Thanks for pointing it out, I'll look into it.

**Comment by PanosK92** [comment]
Self-shadowing has been fixed.

![Capture](https://user-images.githubusercontent.com/19988988/55519999-2a73bf80-5672-11e9-830c-a65b48219f50.PNG)

I'll leave this issue open as shadow cascades also need some work.

**Comment by PanosK92** [comment]
The shadow cascades now cover the entire camera frustum without any problems and zero shadow shimmering 😃 

Closing this issue as shadows can be improved in terms of quality but ahave no bugs 😎
