### ISSUE TITLE
Atmospheric scattering 

### ISSUE THREAD

**Issue by OdysseyGuy** [PanosK92/SpartanEngine#18]
One of the feature of realistic real-time rendering is Atmospheric scattering.

This is what I have got while going through the Unreal Engine Source code.
Unreal engine uses this technique to Add a kind of volumetric rendering.

<a href="https://github.com/OzgurCerlet/precomputed_atmospheric_scattering_dx11">Here</a> the link to the project (Directx).

**Comment by PanosK92** [comment]
Hi OdysseyCreations,

Atmospheric scattering is a nice feature, I thought I already had it in the roadmap, but apparently I forgot. I don't know when i'll implement it due to the large workload but I've just updated the roadmap with it.

Thanks

**Comment by PanosK92** [comment]
A new issue has been opened: https://github.com/PanosK92/SpartanEngine/issues/114

Atmospheric scattering is happening.
