### ISSUE TITLE
Bloom

### ISSUE THREAD

**Issue by rikseth** [PanosK92/SpartanEngine#21]
The bloom post processing effect doesn't look much realistic. Please look after this matter.

**Comment by PanosK92** [comment]
That's true, the bloom effect needs some more work.

I'll look into it.

**Comment by PanosK92** [comment]
The blockiness has been fixed and the spreadis now a bit more realistic.

![BloomComparison](https://user-images.githubusercontent.com/19988988/58340541-051a5b00-7e44-11e9-8f66-6484292fd42b.png)
