### ISSUE TITLE
Editor run on mac

### ISSUE THREAD

**Issue by xiaomingfun** [PanosK92/SpartanEngine#24]
if you finished on Vulkan , will you consider to build the editor on mac ?

**Comment by xiaomingfun** [comment]
@PanosK92

**Comment by PanosK92** [comment]
Hi xiaomingfun!

Yes, both Linux and Mac as the engine has always been developed in a way that will make it relatively easy to be ported. The only problem is that I don't have a Mac so it probably won't happen soon.
