### ISSUE TITLE
Removing a Light component causes a crash

### ISSUE THREAD

**Issue by GPUCode** [PanosK92/SpartanEngine#27]
### Bug description
While testing the engine after I implemented Data Oriented Design, I discovered a bug in which when you remove a light component from an entity the program crashes. At first I thought that I had broken something so, I cloned a fresh copy of master, compiled it and the bug was still there.

### Step to reproduce
Open the engine and add a new blank enitity or a basic shape (cube, quad ...), add a new light component to it, then click the gear icon and click on the Remove option. The program immediately crashes.

### Possible causes
An exception is caused in the Renderer_Passes.cpp file by a light component being nullptr. I think  this is caused because when removing a light component the entity is not removed from the list of light_entities and when the renderer tries to access the component an exception is caused.

![Bug](https://user-images.githubusercontent.com/47210458/62951443-afc26a00-bdf2-11e9-9176-e2a1eb59b443.png)

**Comment by PanosK92** [comment]
Fixed!

Thank you for reporting 👍
