### ISSUE TITLE
[Fixed] Speckeld Cascaded Shadows

### ISSUE THREAD

**Issue by Cyw94** [PanosK92/SpartanEngine#31]
Hello! I'm a student who is analyzing your beautiful code.
Firstly, sorry to my bad English.
Secondly, I'm sorry if you don't like the random commit at my disposal.
If you don't like it, I'll just put it on the issue category.

I find out speckled cascaded shadow when using original z, not reverse z.
It is a problem caused by the perception of the front face as the back face.
so I added front counter clock wise variable to D3D11_RASTERIZER_DESC.
and if you use original z, front counter clock wise variable is true. otherwise false.

Ah! and i don't know about vulkan things... so i can't update source about vulkan :(

[Problem 1]
![Problem](https://user-images.githubusercontent.com/54325338/63816971-2aec5a00-c975-11e9-8fd8-7eb8e3cd8c9f.jpg)

[Problem 2]
![Problem2](https://user-images.githubusercontent.com/54325338/63816976-30e23b00-c975-11e9-9d36-7e93c4dcd939.jpg)

[Fixed]
![fixed](https://user-images.githubusercontent.com/54325338/63816623-dac0c800-c973-11e9-82a6-9e824c1b34d7.jpg)

If i find another problem, so fix it, i upload again. 

P.S. I deeply appreciate your sharing of your AMESOME CODE !!

**Comment by PanosK92** [comment]
Hello,

Since you already fixed it, could you please do a pull request? Don't worry about Vulkan.

Thank you Cyw94 👍

**Comment by Cyw94** [comment]
Thank you for replying.
I thought that revised codes is pushed fine and just do a pull request.
I haven't used the GitHub much, so if there's a problem, let me know.

**Comment by PanosK92** [comment]
I will review and merge your pull request whenever I get some free time today.
Thank you 😃
