### ISSUE TITLE
Client's script compilation

### ISSUE THREAD

**Issue by rikseth** [PanosK92/SpartanEngine#34]
How do game engines like Unreal Engine compile client written cpp code? I have seen while working on unreal engine that when I press the play button it compiles the CPP code that I have written. How does it does so and then links the code to the game?

**Comment by PanosK92** [comment]
Starting from 4.22, Unreal uses [Live++](https://molecular-matters.com/products_livepp.html).
This tool allows it to directly patch the machine code of the running executable.
