### ISSUE TITLE
[Question] RE engine

### ISSUE THREAD

**Issue by OdysseyCreations** [PanosK92/SpartanEngine#36]
In the tweet..
<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Reverse engineering Resident Evil 2&#39;s engine is starting to pay off. The bloom effect now looks natural while also having a lower cost.<br><br>GithHub: <a href="https://t.co/Rgk5wXKN76">https://t.co/Rgk5wXKN76</a> <a href="https://twitter.com/hashtag/SpartanEngine?src=hash&amp;ref_src=twsrc%5Etfw">#SpartanEngine</a> <a href="https://t.co/7qpyS0pnbE">pic.twitter.com/7qpyS0pnbE</a></p>&mdash; Panos Karabelas (@panoskarabelas1) <a href="https://twitter.com/panoskarabelas1/status/1145531314931666944?ref_src=twsrc%5Etfw">July 1, 2019</a></blockquote>

Though the question is pretty vague but>>>
Where did you get the engine???

**Comment by PanosK92** [comment]
I didn't, I used [RenderDoc](https://renderdoc.org/) to capture a couple of frames and went through them.

![D-Gfjx4WkAA_EMp](https://user-images.githubusercontent.com/19988988/66317768-08eddc00-e912-11e9-9f35-aa1ae41193cd.jpg)

**Comment by OdysseyGameWorks** [comment]
> I didn't, I used [RenderDoc](https://renderdoc.org/) to capture a couple of frames and went through them.
> 
> ![D-Gfjx4WkAA_EMp](https://user-images.githubusercontent.com/19988988/66317768-08eddc00-e912-11e9-9f35-aa1ae41193cd.jpg)

Then what is the shader source at the top right corner??

**Comment by OdysseyGameWorks** [comment]
Can I do it for actual games???

**Comment by PanosK92** [comment]
This is an actual game, so you can do it. Some are easier to inject some aren't though.
It looks like you might need to have a look at the [documentation](https://renderdoc.org/docs/index.html) though.

**Comment by OdysseyGameWorks** [comment]
Thanks!!!!!

**Comment by PanosK92** [comment]
![source](https://user-images.githubusercontent.com/19988988/66346486-2ccd1400-e94a-11e9-994d-d9ed80c5ef74.gif)
