### ISSUE TITLE
Constant Buffer Violation

### ISSUE THREAD

**Issue by Kliaxe** [PanosK92/SpartanEngine#37]
Hello, I recently came across your engine project and I immediately became interested. So i read through the system hierarchy and I cant explain how mind opening this is. This is really inspiring and i look forward to go down this path! Your engine structure and design is top notch!
 
So as everyone else would, I began to play around with the engine and decided to add an uniform variable called "white_balance" to the Framebuffer like so:

Renderer.h
```c++
struct FrameBuffer
{
    Math::Matrix view;
    Math::Matrix projection;
    Math::Matrix projection_ortho;
    Math::Matrix view_projection;
    Math::Matrix view_projection_inv;
    Math::Matrix view_projection_ortho;
    Math::Matrix view_projection_unjittered;

    ...

    float ssr_enabled;
    float shadow_resolution;
    float ssao_scale;
    float padding;

    float white_balance;
};
```

And of course to access the uniform variable, I had to create a matching byte count in the shader:

Common_Buffer.hlsl
```hlsl
cbuffer FrameBuffer : register(b0)
{
	matrix g_view;
	matrix g_projection;
	matrix g_projectionOrtho;
	matrix g_viewProjection;
	matrix g_viewProjectionInv;
	matrix g_viewProjectionOrtho;
	matrix g_viewProjectionUnjittered;

        ...
	
	float g_ssr_enabled;
	float g_shadow_resolution;
	float g_ssao_scale;
	float g_padding;

	float g_white_balance;
};
```
As a test only, I assigned a default value of 6500 directly in the UpdateFramebuffer(); funktion:

Renderer.cpp
```c++
...

    m_buffer_frame_cpu.shadow_resolution            = static_cast<float>(m_resolution_shadow);
    m_buffer_frame_cpu.ssao_scale                   = m_options[Option_Value_Ssao_Scale];
    m_buffer_frame_cpu.padding                      = 0.0f;
    m_buffer_frame_cpu.white_balance		    = 6500.0f;

    // Update
    *buffer = m_buffer_frame_cpu;

    // Unmap
    return m_buffer_frame_gpu->Unmap();
```

So now I reckon the shaders should be able to access g_white_balance from the Framebuffer. Unfortunately i got this :(

![image](https://user-images.githubusercontent.com/16865975/69579941-ccfefb00-0fd3-11ea-9528-6643dd3b5489.png)
 
I've tried to debug this issue to its core, from RHI to Renderer, but got no luck. Could be breathtaking if you could educate, not only me but others as well, about this situation. 👍

**Comment by PanosK92** [comment]
Hi Kliaxe,

Thanks for your kind words, I'm glad you find it helpful 😃 

Try removing g_padding from the struct...

```c++
struct FrameBuffer
{
    Math::Matrix view;
    Math::Matrix projection;
    Math::Matrix projection_ortho;
    Math::Matrix view_projection;
    Math::Matrix view_projection_inv;
    Math::Matrix view_projection_ortho;
    Math::Matrix view_projection_unjittered;

    ...

    float ssr_enabled;
    float shadow_resolution;
    float ssao_scale;
    float white_balance;
};
```
... and from the cbuffer

```hlsl
cbuffer FrameBuffer : register(b0)
{
	matrix g_view;
	matrix g_projection;
	matrix g_projectionOrtho;
	matrix g_viewProjection;
	matrix g_viewProjectionInv;
	matrix g_viewProjectionOrtho;
	matrix g_viewProjectionUnjittered;

        ...
	
	float g_ssr_enabled;
	float g_shadow_resolution;
	float g_ssao_scale;
	float g_white_balance;
};
```

It should work now. 

This is because HLSL has some packing/alignment rules for constant buffers (16-byte boundaries), detailed [here](https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-packing-rules).

On top of that, the compiler can choose to add padding to something like a struct, introducing a potential scenario where what you map from the CPU, is different from what the GPU expects.

So it's a good idea to explicitly/manually ensure correct padding both on the CPU and the GPU.

I hope this helps 👍

**Comment by Kliaxe** [comment]
Hello, thank you for the quick answer! Yes, that definitely did the trick!
I'm now closing this issue as the problem has been solved.
