### ISSUE TITLE
[Question] Textures??

### ISSUE THREAD

**Issue by OdysseyCreations** [PanosK92/SpartanEngine#39]
While reading this <a href="https://blogs.unity3d.com/2018/10/08/optimizing-loading-performance-understanding-the-async-upload-pipeline/ ">article</a>, I have found that during build unity puts all the textures to an optimized binary file. 

Now I am developing my own engine (heavily inspired by yours). There I am working on Texture loading. I already have Asynchronous Texture loading which reduced the loading time down to 50%. 

But every time the texture is load stb_image or FreeImage does some post-processing and pre-processing this increases the loading time a lot in case of big textures like 8k Textures. So I was thinking how can I write the texture to a binary format so that once loaded from the second time it loads from the binary and doesn't take much time? 

Now, honestly, I am stuck here since I have googled but didn't find any answer. My only question is how do they do it? Also, I would like to know how will you implement it to your own engine?

**Comment by PanosK92** [comment]
Hi OdysseyCreations,

Have a look at [RHI_Texture](https://github.com/PanosK92/SpartanEngine/blob/master/Runtime/RHI/RHI_Texture.cpp), this is where loading compressed images and serializing/deserializing raw bytes happens.

I understand that you are trying to figure things out so I have created a discord server (link in the project's description) were we can take discussions or questions like this one, which are of a bit more general nature. It will be easier to chat there and at the same time the _issues_ section will contain more directly related content.

Thanks
