### ISSUE TITLE
Log being spammed with Spartan::RHI_CommandList::Gpu_GetMemoryUsed: Failed to get adapter memory info, Unknown error code

### ISSUE THREAD

**Issue by TQwan** [PanosK92/SpartanEngine#40]
Hi, 

When I start the editor the log is being spammed every second with this message:

`
Spartan::RHI_CommandList::Gpu_GetMemoryUsed: Failed to get adapter memory info, Unknown error code`

Note: I am using the VS1019 D3D11 solution, latest checkout. 
Anyway, the error comes from file SpartanEngine\Runtime\RHI\D3D11\D3D11_CommandList.cpp line 737.

It's because my GPU does not seem to support this call.

To fix we could do either tree things.
1. Skip the method if same call previously had an error. (e.g add a boolean variable and set this when failed, then just check if boolean was set before calling the method)
2. Check for gpu features beforehand and not do the call at all (I don't know if this is possible for D11)
3. Add a timestamp check to only skip the log error.
This allows the error to only be shown if it occured at different points in time.

Pseudocode 
```
if (FAILED(result))
{
    if (now > lastErrortimestamp + 1000)
    {
        LOG_ERROR("Failed to get adapter memory info, %s", d3d11_utility::dxgi_error_to_string(result));
    }
    
    lastErrortimestamp = now;
    return 0;
...
```
note: This last option could also be implement globally by changing the LOG_error macro to use a dictionary (error,timestamp).

**Comment by PanosK92** [comment]
Hi TQwan,

Thanks for the update and for the suggestions on how to fix it. 
Before I take care of it, could you please tell me what's your GPU ?

Thanks

**Comment by TQwan** [comment]
ATI Radeon HD 5970

**Comment by PanosK92** [comment]
This [commit](https://github.com/PanosK92/SpartanEngine/commit/bed0c36a6e1e43d19cbb471ad099e8178b9bf6ea) fixes the spamming by using the first approach.

Would be helpful if you could verify that you now get the error message once, and then the memory readings are simply 0.

**Comment by TQwan** [comment]
Thanks, that fixed the problem.
