### ISSUE TITLE
Vulkan validation error

### ISSUE THREAD

**Issue by happydpc** [PanosK92/SpartanEngine#41]
Using Windows 10, GTX2070s, and compiled the master.
![image](https://user-images.githubusercontent.com/771776/89031993-3951ab80-d366-11ea-9589-40aea9c2a330.png)

**Comment by PanosK92** [comment]
Thanks for reporting this, will have a look at it over the weekend.

**Comment by happydpc** [comment]
The release build hasn't this error. But the model is flickering, tried the primitive and gltf model.

**Comment by PanosK92** [comment]
The validation error is fixed.

I am looking into other issues like the flickering you mentioned, if you manage to narrow it down, feel free to open another issue.

**Comment by PanosK92** [comment]
Model flickering has been fixed too
