### ISSUE TITLE
Vulkan Validation Error

### ISSUE THREAD

**Issue by BhayanakMoth** [PanosK92/SpartanEngine#53]
Using RTX3060M  
getting this on the master branch  

Vulkan: Validation Error: [ SYNC-HAZARD-READ_AFTER_WRITE ] Object 0: handle = 0xe150c50000000097, name = rt_ssr, type = VK_OBJECT_TYPE_IMAGE_VIEW; | MessageID = 0x4cb75b2d | vkCmdDrawIndexed: Hazard READ_AFTER_WRITE for VkImageView 0xe150c50000000097[rt_ssr], in VkCommandBuffer 0x1c57e2a8d70[cmd_list], and VkPipeline 0x1faae500000001ca[Pass_Light_ImageBased_Opaque], VkDescriptorSet 0x3d7c1e0000000254[CS:null-VS:ImGui.hlsl-PS:ImGui.hlsl], type: VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE, imageLayout: VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL, binding #231, index 0. Access info (usage: SYNC_FRAGMENT_SHADER_SHADER_STORAGE_READ, prior_usage: SYNC_COMPUTE_SHADER_SHADER_STORAGE_WRITE, write_barriers: 0, command: vkCmdDispatch, seq_no: 27, reset_no: 2887).

![Spartan_vulkan_debug_AWJrIVkVIt](https://user-images.githubusercontent.com/17413156/160284510-0be2e49e-11cf-42e7-94a7-e77bcf31cc79.png)

**Comment by PanosK92** [comment]
It's synchronisation issue related to a render target not transitioning to a layout correctly. It's a known issue so I am looking at this once in a while. Thanks for letting me know.

**Comment by PanosK92** [comment]
This has been fixed. Thanks for reporting.
