### ISSUE TITLE
TAA velocity sample pos is no current pixel pos.

### ISSUE THREAD

**Issue by qiutanguu** [PanosK92/SpartanEngine#56]
Hi, PanosK92.

on temporal_antialiasing.hlsl line#396.  the pos_screen has [-1,-1] offset with center pixel, and u use pos_screen sample velocity at line#339.

i guess u want to sample current pixel's velocity, so why no just use thread_id? and pos_screen != thread_id, or there are some deeper reason i don't know?

**Comment by PanosK92** [comment]
Hi qiutanguu,

You are right, that's a mistake I made.

71d1db6949a1003e7ba53c61b13bad1fcd02c234 corrects this.

Thanks for letting me know !
