### ISSUE TITLE
Editor crash on startup. No camera seems to be found.

### ISSUE THREAD

**Issue by IgnacioMGarrido** [PanosK92/SpartanEngine#57]
No camera seems to be found on engine startup in <Renderer::Pass_Line>. Just pulled the engine recently and I am not familiar with the codebase at all. Got a PR up that seems to solve the issue for me but this seems more like a patch and the issue might lie deeper. 

PR: #58 

### Reproduce
- Clone the repo
- Generate Visual Stuido solution.
- Build Project
- Run Editor

### 

![image](https://user-images.githubusercontent.com/12410116/168479597-87bf7c0d-861b-4f29-8da5-2995e22900df.png)

```
	Spartan_d3d11_debug.exe!Spartan::IComponent::GetTransform() Line 98	C++
 	Spartan_d3d11_debug.exe!Spartan::Renderer::Pass_Lines(Spartan::RHI_CommandList * cmd_list, Spartan::RHI_Texture * tex_out) Line 1868	C++
 	Spartan_d3d11_debug.exe!Spartan::Renderer::Pass_Main(Spartan::RHI_CommandList * cmd_list) Line 170	C++
 	Spartan_d3d11_debug.exe!Spartan::Renderer::OnTick(double delta_time) Line 403	C++
 	Spartan_d3d11_debug.exe!Spartan::Context::OnTick(Spartan::TickType tick_group, double delta_time) Line 129	C++
 	Spartan_d3d11_debug.exe!Spartan::Engine::Tick() Line 91	C++
 	Spartan_d3d11_debug.exe!Editor::Tick() Line 241	C++
 	Spartan_d3d11_debug.exe!WinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance, char * lpCmdLine, int nCmdShow) Line 31	C++

```

### System
OS: Windows 11
CPU: AMD Ryzen 7 5800X, 3801 Mhz
GPU: NVIDIA GeForce RTX 3080

**Comment by PanosK92** [comment]
Thanks for reporting this, and with a great description as well.

Lots of rendering changes lately, due to trying to get Vulkan to be stable.
Missed that null pointer.

Your PR has been merged.

**Comment by IgnacioMGarrido** [comment]
Glad to help! I just started playing around with the engine and this is great, so insightful! Will try to report and hopefuly fix the issues I might find in the process.
