### ISSUE TITLE
Editor crashes when there is a light source and no camera in the scene

### ISSUE THREAD

**Issue by IgnacioMGarrido** [PanosK92/SpartanEngine#59]
# Editor Crashes when there is a light source and a there is no camera in the scene

## Reproduce Issue
There are different ways to reproduce this issue:

### First
- Open editor in the default scene.
- Remove camera from the scene.

#### Result:
- Editor Crashes.

#### Expected behavior:
- Editor keeps running with a some kind of default viewport camera that cannot be removed.

### Second
- Go to World -> New in the menu bar
- Editor Crashes.

#### Result:
- Editor Crashes.

#### Expected behavior:
- Creates a new level with default entities (Environment, Directional Light and Camera).

## 

![image](https://user-images.githubusercontent.com/12410116/168482704-0541cefc-b2bc-41e6-b7dc-ca05bb6b394e.png)

```
 Spartan_d3d11_debug.exe!Spartan::IComponent::GetTransform() Line 98	C++
 Spartan_d3d11_debug.exe!Spartan::Renderer::Pass_Icons(Spartan::RHI_CommandList * cmd_list, Spartan::RHI_Texture * tex_out) Line 1980	C++
 Spartan_d3d11_debug.exe!Spartan::Renderer::Pass_Main(Spartan::RHI_CommandList * cmd_list) Line 172	C++
 Spartan_d3d11_debug.exe!Spartan::Renderer::OnTick(double delta_time) Line 403	C++
 Spartan_d3d11_debug.exe!Spartan::Context::OnTick(Spartan::TickType tick_group, double delta_time) Line 129	C++
 Spartan_d3d11_debug.exe!Spartan::Engine::Tick() Line 91	C++
 Spartan_d3d11_debug.exe!Editor::Tick() Line 241	C++
 Spartan_d3d11_debug.exe!WinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance, char * lpCmdLine, int nCmdShow) Line 31	C++
```

### System
OS: Windows 11
CPU: AMD Ryzen 7 5800X, 3801 Mhz
GPU: NVIDIA GeForce RTX 3080

**Comment by PanosK92** [comment]
Thanks and nice idea to create the default objects upon creating a new world 👍🏻
