### ISSUE TITLE
Linux port questions

### ISSUE THREAD

**Issue by IkerGalardi** [PanosK92/SpartanEngine#63]
Hi! Want to try to port the engine to Linux but I have several questions:

* How do shaders get compiled into spirv? Does the engine use dxcompiler? If that's the case linux builds should use a different approach.

* Using a different sound library would be a pain to implement? As far as I've seen FMod is a proprietary library so having it working on Linux reliably can be a pain in the but.

**Comment by PanosK92** [comment]
Hi!

You more than welcome too.

- The engine uses DirectXShaderCompiler. My understanding is that you can also use it on Linux, right?
- I am using SDL for input and windows, I think it also has audio support, so we good use that and remove FMod.

FYI: Vulkan is not very stable yet as I am adding some finishing touches, but it works.

**Comment by IkerGalardi** [comment]
Cool! I'll start by fixing some minor issues with the project generator (some scripts not having the correct permissions, etc) and sending a pull request. And when I have more time I can start to implement audio using SDL instead. From that point on there should not be any difficulties (fingers crossed).

**Comment by PanosK92** [comment]
Sounds good, don't worry about the time or even doing it at all, just have some fun. If we can get it to generate a project on Linux, even if it doesn't compile, it's still a great step, we could merge it into the repository.

I'm closing this issue, feel free to join our Discord server if you need to talk about anything else.
