### ISSUE TITLE
Bug: resizing editor breaks framebuffer

### ISSUE THREAD

**Issue by IkerGalardi** [PanosK92/SpartanEngine#69]
Spartan Editor opens up maximized. Trying to create a smaller window breaks the editor as shown in the next image:

![image](https://user-images.githubusercontent.com/27565092/175111112-f475f0b9-7ba1-4f5d-a55b-659e3c1c5fcc.png)

The console throws an error: `Spartan::RHI_SwapChain::Resize: Failed to resize swapchain buffers, DXGI_ERROR_INVALID_CALL`

## Useful information

* Windows 11
* DirectX 11

## Steps to reproduce
1. Open spartan (should open maximized)
2. Make a smaller window with the window controls

**Comment by PanosK92** [comment]
Commit feb14ddd33a3105fe01a474860da6842ea5cb60a fixes the issue.

Thanks for reporting this.
