### ISSUE TITLE
Vulkan build freezes during editor startup

### ISSUE THREAD

**Issue by Calinou** [PanosK92/SpartanEngine#72]
**OS:** Windows 10 20H2
**GPU:** NVIDIA GeForce GTX 1080 (driver version 456.71)

I installed both the MSVC 2022 redistributable and the Vulkan SDK and rebooted. When starting the https://github.com/PanosK92/SpartanEngine/commit/1e13e23b43c4a909c68f99fa8b66c41b76395c34 Vulkan build on https://github.com/PanosK92/SpartanEngine/releases, I get the following error:

![image](https://user-images.githubusercontent.com/180032/178163292-ec2b0405-20c5-4882-9440-6b3b011d28c9.png)

The Direct3D 12 build starts, but it exits immediately after. `log.txt` only contains:

```
Info: Spartan::Threading::Threading: 7 threads have been created
Info: Spartan::Renderer::SetOption: Enabled TAA since FSR 2.0 does it.
Info: Spartan::Renderer::SetOption: Enabled FSR 2.0 since it's used for TAA.
Info: Spartan::RHI_Device::RegisterPhysicalDevice: NVIDIA GeForce GTX 1080 (8079 MB)
Info: Spartan::RHI_Device::RegisterPhysicalDevice: Microsoft Basic Render Driver (0 MB)
Info: Spartan::Timer::SetFpsLimit: Set to 59.95 FPS
Info: Spartan::Timer::SetFpsLimit: Set to 99.95 FPS
Info: Spartan::Timer::SetFpsLimit: Set to 119.88 FPS
Info: Spartan::Timer::SetFpsLimit: Set to 120.00 FPS
Info: Spartan::Timer::SetFpsLimit: Set to 143.91 FPS
Info: Spartan::RHI_Device::SetPrimaryPhysicalDevice: NVIDIA GeForce GTX 1080 (8079 MB)
Info: Spartan::RHI_Device::RHI_Device: DirectX 12.0
```

PS: I did get Spartan's Vulkan build to run on Linux via WINE (on the same machine). While it displayed something on screen, it constantly caused the GPU to hang whenever the window was resized.

**Comment by Calinou** [comment]
Fixed by updating graphics driver to 516.29. That'll teach me for booting Windows once a year on average 🙂

**Comment by PanosK92** [comment]
Hi,

I don't know what's wrong, try building the debug configuration and see if you get any errors.

As for the D3D12 build, it's not finished yet, skip it for now.

**Comment by Calinou** [comment]
I compiled a debug build of https://github.com/PanosK92/SpartanEngine/commit/f886b606397f61200b1005d9f7a73fdfc7b2902a with Visual Studio 2022, this is what I get after the editor opens and I try to load a model:

![image](https://user-images.githubusercontent.com/180032/178291555-43816dfc-dee1-4d99-955c-f4c8ae8ea587.png)

(I also had an assertion failure about FMOD which I chose to ignore, since I don't intend on using audio. Is there a CLI argument or build option to disable FMOD?)

**Comment by PanosK92** [comment]
If you ignore the assert does the editor continue as normal? If so, could you copy and paste here, the first error from the console window?

**Comment by PanosK92** [comment]
I was able to reproduce the validation errors, will be fixing them, thank you for reporting them !

**Comment by PanosK92** [comment]
I have some more work to do but 5026e598b68930ac956ae95498938e69d9bbad80 should allow you to run the editor.

**Comment by Calinou** [comment]
> I have some more work to do but [5026e59](https://github.com/PanosK92/SpartanEngine/commit/5026e598b68930ac956ae95498938e69d9bbad80) should allow you to run the editor.

I get this error as of https://github.com/PanosK92/SpartanEngine/commit/e0f66ea41d205877d7bca47b9f74cb07a01e793b:

![spartan_vulkan_debug_naTBGG7sXl](https://user-images.githubusercontent.com/180032/178361291-8879b90e-6107-462d-a7cc-b071d7b27f3d.png)

This is strange, as my GPU (Pascal) should support FP16 instructions. Do I need to clear shader cache manually or something?

**Comment by PanosK92** [comment]
Wasn't expecting this but this appears to be the case, check this out: http://vulkan.gpuinfo.org/displayreport.php?id=15783#features_core_12

FP16 is used by FSR 2 for performance but I will fallback F32 since it's genuinely needed.

Thanks once again !

**Comment by Calinou** [comment]
> FP16 is used by FSR 2 for performance but I will fallback F32 since it's genuinely needed.

Strange, I thought Pascal GPUs supported FP16.

**Comment by PanosK92** [comment]
I don't know a lot about its architecture but, it turns out, that FSR 2.0, will automatically query your GPU for FP16 support, and fall back to FP32 if it doesn't support it. Which means, that I shouldn't be so strict and assert there, hence this ed6197dda78230c98402fae4afe7e6f06ea42bbf commit fixes that.

Whenever you have the time, I would appreciate your help trying to run the editor and let me know if it blows up on you again.

**Comment by PanosK92** [comment]
Quite a few Vulkan errors have been fixed.

If it's not too much trouble, it would be helpful if you could verify if the editor starts properly or not.

**Comment by PanosK92** [comment]
Got my hands on an Nvidia GPU and fixed all start-up asserts.

Due to inactivity I'll assume that this issue has been closed by now and close it.

**Comment by Calinou** [comment]
I can get the development build of https://github.com/PanosK92/SpartanEngine/commit/726db4553e7391c3f229fabc38001ed316eab337 to run, but I only see a flickering white screen:

![image](https://user-images.githubusercontent.com/180032/181865367-d6e73c47-2a4d-4e14-b516-ac765042dc45.png)

Specific GUI elements (like the ImGui style editor window) will also flicker in and out every frame depending on their position.

**Comment by PanosK92** [comment]
Ah yes, this is a synchronisation issue that I am trying to solve, the last major problem. I'll open an issue for it.

Thanks for getting back to me !
