### ISSUE TITLE
RenderDoc capture not working for the D3D11 Backend

### ISSUE THREAD

**Issue by gmodarelli** [PanosK92/SpartanEngine#87]
Hello there, I was trying to capture a frame in RenderDoc from within the engine, but unfortunately RenderDoc simply hangs.

I see this error in Visual Studio. 
```
RDOC 038124: [16:21:50] d3d11_context_wrap.cpp(3003) - Error   - Assertion failed: 'ppRenderTargetViews[i] == m_CurrentPipelineState->OM.RenderTargets[i]'
```
I've tried to debug it but couldn't find the issue.

**Comment by PanosK92** [comment]
Prego!
