### ISSUE TITLE
Array out of range assert hit on editor startup

### ISSUE THREAD

**Issue by gmodarelli** [PanosK92/SpartanEngine#92]
Hello, I'm hitting an array out of range assertion when I try to start the editor in debug mode with the DirectX 11 backend.

This is caused by the `RHI_SwapChain::GetLayout()` function trying to access the `m_layouts` array with the `m_image_index` set to `uint32_t::max`
https://github.com/PanosK92/SpartanEngine/blob/master/runtime/RHI/RHI_SwapChain.h#L71

I've added a memory breakpoint as suggested on Discord, and could verify that `m_image_index` is never updated after being initialized to `uint32_t::max`.

As a workaround, I've commented out the call to the `RHI_SwpaChain::GetLayout()` function from the `Renderer::Present()` function.

![image](https://user-images.githubusercontent.com/579525/236630845-5c853a82-a6f3-45a5-a371-a6c6192e5872.png)
![image](https://user-images.githubusercontent.com/579525/236630852-95811272-9c28-4510-baa1-d0a6fdaa003e.png)

**Comment by PanosK92** [comment]
29042da fixes the issue.

Thanks for letting me know 👍🏻
