### ISSUE TITLE
Delete key unusable when deleting a transform value.

### ISSUE THREAD

**Issue by NickPolyder** [PanosK92/SpartanEngine#94]
Hello there,

While playing with the Transform properties
![image](https://github.com/PanosK92/SpartanEngine/assets/7039167/c2b34b6e-b177-453c-a096-3468086e602b)
Modifying any of the values in there and then pressing Delete will force the Deletion of the Entity (Helmet for example)
Which then in turn will generate an exception because one cannot modifying something that is being deleted.

I believe the origin of the issue comes from the HotKeys being mapped into single key instead of a combination key.

**Comment by PanosK92** [comment]
d75225d fixes the exceptions.

However, there is yet another exception after that (also happens during engine shutdown), so I'll leave this issue open.

Thanks for reporting this 👍🏻

**Comment by PanosK92** [comment]
d6c1b2e fixes the remaining crash.
